# Menu
# menu:
  # Home: /
  # Archives: /archives
  # About: /about

# Read More text
excerpt_link: Read More

# Disqus Comments Shortname
disqus_shortname:

# Duoshuo Comments Shortname
# duoshuo_shortname: sinchang

# Google Analytics Tracking ID(example:UA-83746351-2)
google_analytics:

# Social Media
