# Menu
# menu:
  # Home: /
  # Archives: /archives
  # About: /about

# Read More text
excerpt_link: Read More

# Disqus Comments Shortname
disqus_shortname:

# Duoshuo Comments Shortname
# duoshuo_shortname: sinchang

# Google Analytics Tracking ID(example:UA-83746351-2)
google_analytics:

# Social Media
# twitter: sinchangwen
# weibo: 772608204
# facebook:
# github: sinchang
# email: sinchangwen@gmail.com
# instagram: sinchangwen
# url: weixin: http://ooo.0o0.ooo/2016/05/21/574012ec9069d.png
